"""empty message

Revision ID: df0b359ee0e2
Revises: 
Create Date: 2022-10-31 07:05:15.834797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df0b359ee0e2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "description")
    # ### end Alembic commands ###
